init
alibabacloud-automation/terraform-alicloud-polardb-mysql pull request #1
Opened 2022-03-23 05:59 UTC by susu9527

2022-03-26 10:47 UTC, xiaozhu36 requested changes

2022-03-26 10:47 UTC, xiaozhu36 commented on main.tf
> +  region = "cn-hangzhou"
module 中不要定义 provider

2022-03-26 10:47 UTC, xiaozhu36 commented on variables.tf
> +  default     = "16:00Z-17:00Z"
这个设置为 null

2022-03-26 10:47 UTC, xiaozhu36 commented on variables.tf
> +  default     = ["Tuesday","Thursday", "Saturday"]
这个也设置为 null

2022-03-26 10:47 UTC, xiaozhu36 commented on variables.tf
> +  default     = "02:00Z-03:00Z"
还有这个

2022-03-26 10:47 UTC, xiaozhu36 commented on outputs.tf
> +  description = "The ip address of connection string."
polardb 这个前缀去掉

2022-03-26 10:47 UTC, xiaozhu36 commented on variables.tf
> +variable "database_id" {
变量中的ID只保留 cluster id 就行，其他的去掉

2022-03-28 02:31 UTC, susu9527 commented on variables.tf
> +  default     = "16:00Z-17:00Z"
ok

2022-03-28 02:31 UTC, susu9527 commented on variables.tf
> +  default     = ["Tuesday","Thursday", "Saturday"]
ok

2022-03-28 02:39 UTC, susu9527 commented on variables.tf
> +variable "database_id" {
ok

2022-03-28 02:39 UTC, susu9527 commented on outputs.tf
> +  description = "The ip address of connection string."
ok

2022-03-28 02:39 UTC, susu9527 commented on variables.tf
> +  default     = "02:00Z-03:00Z"
done

2022-03-28 03:25 UTC, xiaozhu36 requested changes

2022-03-28 03:25 UTC, xiaozhu36 commented on locals.tf
> +  this_database_id = var.create_database ? concat(alicloud_polardb_database.database.*.db_name, [""])[0] : var.database_id
只保留 var.db_cluster_id，其他的 var.db_endpoint_id， var.db_account_id，var.database_id 都不要，都从 variables 中删掉，直接用新创建的

2022-03-28 06:10 UTC, xiaozhu36 requested changes

2022-03-28 06:10 UTC, xiaozhu36 commented on main.tf
> +    Created = "TF"
这个也一样

2022-03-28 06:10 UTC, xiaozhu36 commented on main.tf
> +  db_name            = var.name
这个name 也一样

2022-03-28 09:12 UTC, merged