terraform module support added attribute of resource resource_alicloud_polardb_cluster、resource_alicloud_polardb_backup_policy
alibabacloud-automation/terraform-alicloud-polardb-mysql pull request #10
Opened 2024-04-15 10:44 UTC by mengliux

terraform module support added attribute of resource resource_alicloud_polardb_cluster、resource_alicloud_polardb_backup_policy

2024-04-26 09:34 UTC, xiaozhu36 requested changes

2024-04-26 09:34 UTC, xiaozhu36 commented on README-CN.md
> +* [从polardb克隆实例 示例](https://github.com/terraform-alicloud-modules/terraform-alicloud-polardb-mysql/tree/main/examples/clone-from-polardb)
上面的那个示例是不是写错了，应该不是 Clickhouse 吧

2024-04-26 09:34 UTC, xiaozhu36 commented on outputs.tf
> +  description = "The edition of the PolarDB service.."
这个后面为啥有两个点号

2024-04-26 09:34 UTC, xiaozhu36 commented on variables.tf
> +  default     = "Private"
这个默认值为啥要改

2024-04-26 09:34 UTC, xiaozhu36 commented on variables.tf
> +  description = "The retention period of cross-region log backups. Default value: OFF. Valid values are `0`, `30 to 7300`, `-1`."
这个描述不对吧，Default 是 OFF，但是valid values中又不包含 OFF

2024-04-26 09:55 UTC, mengliux commented on variables.tf
> +  default     = "Private"
因为实例创建后，每种endpoint都是私网的，所以默认值给个私网。公网在创建后才会有的。

2024-04-26 09:56 UTC, mengliux commented on variables.tf
> +  description = "The retention period of cross-region log backups. Default value: OFF. Valid values are `0`, `30 to 7300`, `-1`."
这个写错了，我改一下。

2024-04-26 10:01 UTC, mengliux commented on outputs.tf
> +  description = "The edition of the PolarDB service.."
写错了，我删一下

2024-04-26 10:20 UTC, mengliux commented on README-CN.md
> +* [从polardb克隆实例 示例](https://github.com/terraform-alicloud-modules/terraform-alicloud-polardb-mysql/tree/main/examples/clone-from-polardb)
可能以前写错了，我改掉

2024-04-28 07:55 UTC, xiaozhu36 requested changes

2024-04-28 07:55 UTC, xiaozhu36 commented on variables.tf
> +  default     = "Private"
修改默认值这个属于非兼容的变更。 这个地方不改会有什么问题么？

2024-04-28 08:09 UTC, mengliux commented on variables.tf
> +  default     = "Private"
example 跑测试时候，会报ssl 修改失败，因为ssl 修改时候传的是公网public，但是实际当前公网未创建只有私网

2024-04-29 10:48 UTC, xiaozhu36 approved these changes

2024-04-30 01:45 UTC, merged