examples/dbCluster: Added attributes about backup_policy.
alibabacloud-automation/terraform-alicloud-polardb-mysql pull request #3
Opened 2023-10-31 02:37 UTC by mengliux

examples/dbCluster: Added attributes about backup_policy.

2023-10-31 05:58 UTC, xiaozhu36 requested changes

2023-10-31 05:58 UTC, xiaozhu36 commented on main.tf
> +  parameters {
parameters 在 terraform 中是一个 list，因此如果这个module 需要支持多个参数的话，需要将 parameters 设置为 list（map）

2023-10-31 05:58 UTC, xiaozhu36 commented on examples/complete/main.tf
> +  data_level2_backup_period                   = var.data_level2_backup_period
parameters 这个参数在example 中没有体现

2023-10-31 09:22 UTC, mengliux commented on main.tf
> +  parameters {
改了

2023-10-31 09:23 UTC, mengliux commented on examples/complete/main.tf
> +  data_level2_backup_period                   = var.data_level2_backup_period
加了

2023-10-31 09:42 UTC, mengliux commented
测试结果：https://aliyuque.antfin.com/wb-lm659441/ry4io0/mtrhu78v5ibmz3zf?singleDoc# 《TF  module 支持备份策略》

2023-11-01 06:59 UTC, xiaozhu36 approved these changes

2023-11-01 07:00 UTC, merged